use crate::Algorithm;
use core::fmt;

/// Represents a token generated by [`Totp`](crate::Totp).
/// This can be thought of as a string with a few notable difference:
///
/// * It is _only_ stack allocated
/// * Comparison is done in constant time regardless of the number of digits in the token
/// * Formatting is lazily evaluated
///
/// Since it implements [`Display`](core::fmt::Display), it can be directly
/// used in formatting just like a string:
///
/// ```
/// # use totp_rs::Token;
/// # extern crate alloc;
/// # use alloc::{format, string::String};
/// # #[cfg(feature = "alloc")]
/// # fn _foo(token: Token) {
/// let text: String = format!("{}", token);
/// # }
/// ```
///
/// While [`Token`] implements [`Eq`], it's strongly recommended that you rely on
/// [`check`](crate::Totp::check) instead, as that will take skew into account.
///
/// Note that while [`Token`] is stack-allocated and only contains plain data, it
/// does _not_ implement [`Copy`].
/// This is to preserve compatibility with the `zeroize` feature which will add
/// a non-trivial [`Drop`] implementation.
#[derive(Clone, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "zeroize", derive(zeroize::Zeroize, zeroize::ZeroizeOnDrop))]
pub struct Token {
    #[cfg_attr(feature = "zeroize", zeroize(skip))]
    algorithm: Algorithm,
    #[cfg_attr(feature = "zeroize", zeroize(skip))]
    digits: u8,
    /// # Invariants
    ///
    /// * `self.value == self.value & 0x7FFF_FFFF;`
    /// * `self.value == self.value % Self::modulo(self.algorithm, self.digits);`
    value: u32,
}

impl Token {
    pub(crate) const fn new(algorithm: Algorithm, digits: u8, value: u32) -> Self {
        Self {
            algorithm,
            digits,
            value: (value & 0x7FFF_FFFF) % Self::modulo(algorithm, digits),
        }
    }

    pub(crate) const fn from_signature(algorithm: Algorithm, digits: u8, signature: &[u8]) -> Self {
        let last = *signature.last().unwrap();
        let offset = (last & 0xF) as usize;
        let value = u32::from_be_bytes([
            signature[offset],
            signature[offset + 1],
            signature[offset + 2],
            signature[offset + 3],
        ]);

        Self::new(algorithm, digits, value)
    }

    pub(crate) const fn try_from_formatted_string(
        algorithm: Algorithm,
        digits: u8,
        string: &str,
    ) -> Option<Self> {
        if string.len() != digits as usize {
            return None;
        }

        let value = match algorithm {
            Algorithm::SHA1 | Algorithm::SHA256 | Algorithm::SHA512 => {
                match u32::from_str_radix(string, 10) {
                    Ok(value) => value,
                    Err(_) => return None,
                }
            }
            #[cfg(feature = "steam")]
            Algorithm::Steam => {
                let radix = STEAM_CHARS.len();
                let mut value = 0;
                let mut place = 1;
                let mut bytes = string.as_bytes();
                while let [byte, rest @ ..] = bytes {
                    let mut i = 0;
                    let mut digits = STEAM_CHARS;
                    while let [x, rest @ ..] = digits {
                        if *x == *byte {
                            value += i * place;
                            break;
                        } else {
                            i += 1;
                            digits = rest;
                        }
                    }

                    bytes = rest;
                    place *= radix;
                }

                value as u32
            }
        };

        Some(Self::new(algorithm, digits, value))
    }

    const fn modulo(algorithm: Algorithm, digits: u8) -> u32 {
        match algorithm {
            Algorithm::SHA1 | Algorithm::SHA256 | Algorithm::SHA512 => 10_u32.pow(digits as u32),
            #[cfg(feature = "steam")]
            Algorithm::Steam => (STEAM_CHARS.len() as u32).pow(digits as u32),
        }
    }
}

impl PartialEq for Token {
    // [`algorithm`](Token::algorithm) and [`digits`](Token::digits) are not considered
    // secret, so their comparison need not be constant time.
    fn eq(&self, other: &Self) -> bool {
        constant_time_eq::constant_time_eq_n(&self.value.to_ne_bytes(), &other.value.to_ne_bytes())
            && self.algorithm == other.algorithm
            && self.digits == other.digits
    }
}

impl fmt::Debug for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        <Self as fmt::Display>::fmt(self, f)
    }
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.algorithm {
            Algorithm::SHA1 | Algorithm::SHA256 | Algorithm::SHA512 => write!(
                f,
                "{1:00$}",
                self.digits.into(),
                self.value % 10_u32.pow(self.digits.into())
            ),
            #[cfg(feature = "steam")]
            Algorithm::Steam => {
                use core::fmt::Write as _;

                let chars = (0..self.digits).scan(self.value, |value, _| {
                    let digit = *value as usize % STEAM_CHARS.len();
                    *value /= STEAM_CHARS.len() as u32;
                    Some(char::from(STEAM_CHARS[digit]))
                });

                for c in chars {
                    f.write_char(c)?;
                }

                Ok(())
            }
        }
    }
}

/// Alphabet for Steam tokens.
#[cfg(feature = "steam")]
const STEAM_CHARS: &[u8] = b"23456789BCDFGHJKMNPQRTVWXY";

